# Site settings
title: İsmail Demirbilek
description: © 2015 İsmail Demirbilek.
baseurl: "/" # the subpath of your site, e.g. /blog/
# url: http://ismaildemirbilek.com # comment it on localhost
permalink: /:title

# Build settings
markdown: kramdown
paginate: 8 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: pygments
gems: [jekyll-paginate, jekyll-coffeescript]

# comments
disqus: dbtek

# author info
# add your appropriate info here
author:           İsmail Demirbilek
bio:              Software Engineer / Designer
email:            demirbilek.ismail@gmail.com
email_md5:        1ecf09922951ed72da5e0a6b3b12bfc1
twitter_username: dbtek
github_username:  dbtek

# Theming options
# These settings are mandatory.
theme:              'blue_grey-pink'

# drawer theming
drawer:
  header_color:     'blue-700'
  title_color:      'white'
  text_color:       'blue-grey-700'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-300'
  color: 'blue-grey-800'
